
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container, Box } from "@mui/material";

import Header from "../app/components/Header";
import Footer from "../app/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/*  <Box sx={{ display: "flex", flexDirection: "column", minHeight: "100vh" }}> */}
            {/* Another Content Section */}
        <Container sx={{ flexGrow: 1, py: 4, bgcolor: "#FFFFFF", boxShadow: 2, borderRadius: 1 }}>
          <Header />
          <Box sx={{ bgcolor: "#ffffff", minHeight: "100vh" }}>{children}</Box>
          <Footer />
        </Container>

        {/* </Box> */}
      </body>
    </html>
  );
}
